/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Class.UserClass;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author faish
 */
public class DataPeminjaman extends javax.swing.JFrame {

    private static final String DB_URL = "jdbc:mysql://localhost/db";
    private static final String USER = "root";
    private static final String PASS = "Qa04091518";

    private static Connection conn;
    private static Statement stmt;
    private static ResultSet rs;
    
    String _username;
    String _role;
    /**
     * Creates new form DataPeminjaman
     */
    public DataPeminjaman(String username, String role) {
        initComponents();
        
        this._username = username;
        this._role = role;
        
        if(role.equals("Regular User")) {
            jButton8.setVisible(false);
        }
        
        try {
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            stmt = conn.createStatement();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        
        if (role.equals("Regular User")) {
            jButton7.setVisible(false);
            jButton6.setVisible(false);
        }
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1288, 816));

        jPanel2.setBackground(new java.awt.Color(178, 45, 48));

        jLabel1.setBackground(new java.awt.Color(178, 45, 48));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Logistik");

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/right-arrow.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        jLabel4.setText("Data Peminjaman");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Transaksi", "Barang", "ID Barang", "Peminjam", "Tanggal Peminjaman", "Lokasi Pinjam", "Status", "Jumlah Barang"
            }
        ));
        jScrollPane5.setViewportView(jTable1);

        jButton4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(178, 45, 48));
        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(178, 45, 48));
        jButton6.setText("Barang Kembali");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(178, 45, 48));
        jButton7.setText("Approve");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(178, 45, 48));
        jButton8.setText("Tolak");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addGap(243, 243, 243))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void loadData() {
        String[] columnNames = {"ID Transaksi", "Nama Barang", "ID Barang", "Nama Peminjam", "Tanggal Peminjaman", "Lokasi Pinjam", "Status Peminjaman", "Jumlah Barang"};
        DefaultTableModel tableModel = new DefaultTableModel(columnNames, 0);

        try {
            Statement stmt = conn.createStatement();
            String query = "SELECT T.ID_TRANSAKSI, B.NamaBarang, T.ID_BARANG, U.Nama, T.TANGGAL_PEMINJAMAN, T.LOKASI_PINJAM, T.JUMLAH_BARANG, T.STATUS_PEMINJAMAN " +
                           "FROM Transaksi T " +
                           "JOIN user U ON T.USERNAME = U.Username " +
                           "JOIN inventory B ON T.ID_BARANG = B.IdBarang";
            ResultSet rs = stmt.executeQuery(query);

            while (rs.next()) {
                String idTransaksi = rs.getString("ID_TRANSAKSI");
                String namaBarang = rs.getString("NamaBarang");
                String idBarang = rs.getString("ID_BARANG");
                String namaUser = rs.getString("Nama");
                String tanggalPeminjaman = rs.getString("TANGGAL_PEMINJAMAN");
                String lokasiPinjam = rs.getString("LOKASI_PINJAM");
                int jumlahBarang = rs.getInt("JUMLAH_BARANG");
                String statusPeminjaman = rs.getString("STATUS_PEMINJAMAN");

                Object[] data = {idTransaksi, namaBarang, idBarang, namaUser, tanggalPeminjaman, lokasiPinjam, statusPeminjaman, jumlahBarang};
                tableModel.addRow(data);
            }
            jTable1.setModel(tableModel);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void updateStatusWithDiKembalikan(String idTransaksi, String statusAwal, String statusAkhir) {
        try {
            // Check if the initial status is "Disetujui"
            if ("Disetujui".equalsIgnoreCase(statusAwal)) {
                // Update status in Transaksi table to "Dikembalikan"
                String updateTransaksiQuery = "UPDATE Transaksi SET STATUS_PEMINJAMAN = ? WHERE ID_TRANSAKSI = ?";
                PreparedStatement pstmtTransaksi = conn.prepareStatement(updateTransaksiQuery);
                pstmtTransaksi.setString(1, statusAkhir);
                pstmtTransaksi.setString(2, idTransaksi);

                // Update inventory stock
                String updateInventoryQuery = "UPDATE inventory i JOIN Transaksi t ON i.IdBarang = t.ID_BARANG " +
                                              "SET i.Stok = i.Stok + t.JUMLAH_BARANG " +
                                              "WHERE t.ID_TRANSAKSI = ?";
                PreparedStatement pstmtInventory = conn.prepareStatement(updateInventoryQuery);
                pstmtInventory.setString(1, idTransaksi);

                // Execute updates
                int transaksiRowsUpdated = pstmtTransaksi.executeUpdate();
                int inventoryRowsUpdated = pstmtInventory.executeUpdate();

                // Check if both updates were successful
                if (transaksiRowsUpdated > 0 && inventoryRowsUpdated > 0) {
                    JOptionPane.showMessageDialog(null, "Status transaksi berhasil diupdate menjadi " + statusAkhir);
                    // Reload data after updating status
                    loadData();
                } else {
                    JOptionPane.showMessageDialog(null, "Gagal mengupdate status transaksi atau menambahkan stok barang.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Status awal bukan 'Disetujui', tidak bisa menjalankan perubahan status.");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }


    }

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow >= 0) {
            String idTransaksi = (String) jTable1.getValueAt(selectedRow, 0);
            String statusAwal = (String) jTable1.getValueAt(selectedRow, 6);
            updateStatusWithDiKembalikan(idTransaksi, statusAwal, "telah kembali");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (jTextField1 != null) {
            String[] columnNames = {"ID Transaksi", "Nama Barang", "ID Barang", "Nama Peminjam", "Tanggal Peminjaman", "Stok", "Status Peminjaman", "Jumlah Barang"};
            DefaultTableModel tableModel = new DefaultTableModel(columnNames, 0);
            String keyword = jTextField1.getText();

            try {
                Statement stmt = conn.createStatement();
                String query = "SELECT T.ID_TRANSAKSI, B.NamaBarang, T.ID_BARANG, U.Nama, T.TANGGAL_PEMINJAMAN, B.Stok, T.JUMLAH_BARANG, T.STATUS_PEMINJAMAN " +
                               "FROM Transaksi T " +
                               "JOIN user U ON T.USERNAME = U.Username " +
                               "JOIN inventory B ON T.ID_BARANG = B.IdBarang " +
                               "WHERE B.NamaBarang LIKE '%" + keyword + "%'";
                ResultSet rs = stmt.executeQuery(query);

                while (rs.next()) {
                    String idTransaksi = rs.getString("ID_TRANSAKSI");
                    String namaBarang = rs.getString("NamaBarang");
                    String idBarang = rs.getString("ID_BARANG");
                    String namaUser = rs.getString("Nama");
                    String tanggalPeminjaman = rs.getString("TANGGAL_PEMINJAMAN");
                    int stokBarang = rs.getInt("Stok");
                    int jumlahBarang = rs.getInt("JUMLAH_BARANG");
                    String statusPeminjaman = rs.getString("STATUS_PEMINJAMAN");

                    Object[] data = {idTransaksi, namaBarang, idBarang, namaUser, tanggalPeminjaman, stokBarang, statusPeminjaman, jumlahBarang};
                    tableModel.addRow(data);
                }

                if (tableModel.getRowCount() == 0) {
                    JOptionPane.showMessageDialog(this, "Barang tidak ditemukan.");
                } else {
                    jTable1.setModel(tableModel);
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed
    
    private void updateStatusWithApprove(String idTransaksi, String statusAwal, String statusAkhir) {
        try {
            // Check if the initial status is pending
            if ("Pending".equals(statusAwal)) {
                // Update status in Transaksi table
                String updateTransaksiQuery = "UPDATE Transaksi SET STATUS_PEMINJAMAN = ? WHERE ID_TRANSAKSI = ?";
                PreparedStatement pstmtTransaksi = conn.prepareStatement(updateTransaksiQuery);
                pstmtTransaksi.setString(1, statusAkhir);
                pstmtTransaksi.setString(2, idTransaksi);

                // Update inventory stock
                String updateInventoryQuery = "UPDATE inventory i JOIN Transaksi t ON i.IdBarang = t.ID_BARANG " +
                                              "SET i.Stok = i.Stok - t.JUMLAH_BARANG " +
                                              "WHERE t.ID_TRANSAKSI = ?";
                PreparedStatement pstmtInventory = conn.prepareStatement(updateInventoryQuery);
                pstmtInventory.setString(1, idTransaksi);

                // Execute updates
                int transaksiRowsUpdated = pstmtTransaksi.executeUpdate();
                int inventoryRowsUpdated = pstmtInventory.executeUpdate();

                // Check if both updates were successful
                if (transaksiRowsUpdated > 0 && inventoryRowsUpdated > 0) {
                    JOptionPane.showMessageDialog(null, "Status transaksi berhasil diupdate menjadi " + statusAkhir);
                    // Reload data after updating status
                    loadData();
                } else {
                    JOptionPane.showMessageDialog(null, "Gagal mengupdate status transaksi atau mengurangi stok barang.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Status awal bukan 'pending', tidak bisa menjalankan perubahan status.");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow >= 0) {
            String idTransaksi = (String) jTable1.getValueAt(selectedRow, 0);
            String statusAwal = (String) jTable1.getValueAt(selectedRow, 6);
            updateStatusWithApprove(idTransaksi, statusAwal, "Disetujui");
            loadData();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        UserClass userClass = new UserClass();
        UserClass.User user;
        
        if ("Admin".equalsIgnoreCase(_role)) {
            user = userClass.new AdminUser(_username, _role);
        } else {
            user = userClass.new RegularUser(_username, _role);
        }

        Dashboard dashboard = new Dashboard(user);
        dashboard.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void updateStatusWithReject(String idTransaksi, String statusAwal, String statusAkhir) {
        try {
            // Check if the initial status is "Pending"
            if ("Pending".equalsIgnoreCase(statusAwal)) {
                // Update status in Transaksi table to "Ditolak"
                String updateTransaksiQuery = "UPDATE Transaksi SET STATUS_PEMINJAMAN = ? WHERE ID_TRANSAKSI = ?";
                PreparedStatement pstmtTransaksi = conn.prepareStatement(updateTransaksiQuery);
                pstmtTransaksi.setString(1, statusAkhir);
                pstmtTransaksi.setString(2, idTransaksi);

                // Execute update
                int transaksiRowsUpdated = pstmtTransaksi.executeUpdate();

                // Check if the update was successful
                if (transaksiRowsUpdated > 0) {
                    JOptionPane.showMessageDialog(null, "Status transaksi berhasil diupdate menjadi " + statusAkhir);
                    // Reload data after updating status
                    loadData();
                } else {
                    JOptionPane.showMessageDialog(null, "Gagal mengupdate status transaksi.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Status awal bukan 'Pending', tidak bisa menjalankan perubahan status.");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow >= 0) {
            String idTransaksi = (String) jTable1.getValueAt(selectedRow, 0);
            String statusAwal = (String) jTable1.getValueAt(selectedRow, 6);
            updateStatusWithReject(idTransaksi, statusAwal, "Ditolak");
            loadData();
        }
    }//GEN-LAST:event_jButton8ActionPerformed
/*    private void deleteTransaction(String idTransaksi) {
        try {
            String deleteQuery = "DELETE FROM Transaksi WHERE ID_TRANSAKSI = ?";
            PreparedStatement pstmt = conn.prepareStatement(deleteQuery);
            pstmt.setString(1, idTransaksi);

            int rowsDeleted = pstmt.executeUpdate();

            if (rowsDeleted > 0) {
                JOptionPane.showMessageDialog(null, "Data transaksi berhasil dihapus.");
                // Reload data after deleting the transaction
                loadData();
            } else {
                JOptionPane.showMessageDialog(null, "Gagal menghapus data transaksi.");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
